export enum actionTypes {
    AUTH_START = 'AUTH_START',
    AUTH_FAIL = 'AUTH_FILE',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_LOGOUT = 'AUTH_LOGOUT',
    SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"
}